/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _CompareRoute } from '../pages/compare';
import { Route as _SavedRoute } from '../pages/saved';
import { Route as _MyRoute } from '../pages/my';
import { Route as _IndexRoute } from '../pages/';
import { Route as _DealDetailRoute } from '../pages/deal-detail';
import { Route as _FlightsRoute } from '../pages/flights';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/compare': (typeof _CompareRoute)['_inputType'];
    '/saved': (typeof _SavedRoute)['_inputType'];
    '/my': (typeof _MyRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/deal-detail': (typeof _DealDetailRoute)['_inputType'];
    '/flights': (typeof _FlightsRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/compare': (typeof _CompareRoute)['_outputType'];
    '/saved': (typeof _SavedRoute)['_outputType'];
    '/my': (typeof _MyRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/deal-detail': (typeof _DealDetailRoute)['_outputType'];
    '/flights': (typeof _FlightsRoute)['_outputType'];
  }
}
